apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8snet
  labels:
    name: k8snet
spec:
  template:
    metadata:
      labels:
        name: k8snet
    spec:
      hostNetwork: true
      containers:
      - name: k8sconntracker
        image: dongyiyang/k8sconntracker:dev
        securityContext:
          privileged: true
        ports:
          - name: http
            containerPort: 2222
            hostPort: 2222
        command:
          - /bin/conntracker
        args:
          - --v=3
          - --master=http://172.17.0.1:8080
          - --enable-flow-collector=false
      restartPolicy: Always
